### PR TITLE
Expose proxy disabling to the command line

### PR DESCRIPTION
**Pull request by BrianMitchL**
I thought it'd be quite useful to have the ability to disable a record from being proxied from the command line. If merged, this would expose the flag behind `--disable_proxied` or `-d`.

Something to consider, should a record be proxied by default (the current and functionality of this PR), or not proxied by default? Personally, I think a flag called `--proxied` makes more sense than `--disable_proxied`, but that could just be me 🤷‍♂️

### CODE REVIEW

**Comment by shlinx** [comment]
Thanks for this, @BrianMitchL. I agree with you being more comfortable with --proxied. However, I think it depends on what the major users would choose by default, proxied or not. Actually, I'm not quite familiar with the downside of using proxied. Would you give your case not using proxied?

**Comment by BrianMitchL** [comment]
One of the services I run behind a subdomain isn't a web service, and will not function when the proxy is enabled. I simply want a DNS record to point to an IP address, without any middleware.

**Comment by BrianMitchL** [comment]
I think that matching the default CloudFlare value would be best. When using the following request to create a new record, it was created with the proxy disabled.

```
curl -X POST "https://api.cloudflare.com/client/v4/zones/:zone_identifier/dns_records" \
     -H "X-Auth-Email: user@example.com" \
     -H "X-Auth-Key: 1234567890" \
     -H "Content-Type: application/json" \
     --data '{"type":"A","name":"test","content":"1.2.3.4"}'
```

Ultimately, I am fine with whichever way you'd like to have the default. Having it be configurable with a command line flag is what I'm most interested in.

**Comment by shlinx** [comment]
@BrianMitchL Right, it'll be good to match the CloudFlare default value. Are you able to change in this to use --proxied? Thanks in advance.

**Comment by BrianMitchL** [comment]
That should do it!

**Pull request merged**
